### ISSUE TITLE
Cannot save bookmarks

### ISSUE THREAD

**Issue by CodingFan72** [osxzxso/extension-bookmarker#1]
Hi,

everytime when I tried to save a bookmark I get the message:

`TypeError: Cannot read properties of undefined (reading 'toFixed')`

What did I wrong?

Greetings

**Comment by osxzxso** [comment]
I just spotted the issue. I had to add a check for when an extension is fetched, but it does not have a rating yet (same for some of the other properties, so I will add checks for all scenarios). I'll push an update in the next few minutes.

**Comment by osxzxso** [comment]
Just pushed version 1.0.2 which should fix the issue you were experiencing. Let me know if you have any other troubles.

**Comment by CodingFan72** [comment]
👍 Thank you very much for the fast fix.
